-- 0015_equipment_items: the centerpiece — one row per individually tracked physical unit.
-- Three distinct identifiers: `id` (internal immutable UUID), `asset_tag` (human-readable,
-- auto-generated via generate_asset_tag()), and the QR/barcode issued later in
-- 0020_equipment_codes_scans_movements.sql (which encode the asset_tag).
--
-- purchase_id has no FK yet — equipment_purchases doesn't exist until 0016, which adds the
-- constraint via ALTER TABLE once it does (same pattern as profiles.location_id in Module 1).

create table public.equipment_items (
  id uuid primary key default gen_random_uuid(),
  model_id uuid not null references public.equipment_models (id),
  asset_tag text not null unique,
  serial_number text,
  purchase_id uuid,
  current_status text not null default 'available' check (
    current_status in ('available', 'reserved', 'in_use', 'in_maintenance', 'damaged', 'lost', 'retired')
  ),
  current_condition text not null default 'new' check (
    current_condition in ('new', 'good', 'fair', 'poor', 'damaged')
  ),
  current_storage_location_id uuid references public.storage_locations (id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles (id),
  updated_by uuid references public.profiles (id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles (id)
);

comment on table public.equipment_items is
  'One row per physical unit (LED Panel #001, Power Cable #002, ...). current_status is workflow/availability; current_condition is physical wear — independent axes.';
comment on column public.equipment_items.asset_tag is
  'Human-readable identifier auto-generated by generate_asset_tag(), e.g. LEDP-000001. Encoded into the item''s QR/barcode.';

create index equipment_items_model_id_idx on public.equipment_items (model_id);
create index equipment_items_purchase_id_idx on public.equipment_items (purchase_id);
create index equipment_items_current_storage_location_id_idx on public.equipment_items (current_storage_location_id);
create index equipment_items_current_status_idx on public.equipment_items (current_status);
create index equipment_items_created_by_idx on public.equipment_items (created_by);
create index equipment_items_updated_by_idx on public.equipment_items (updated_by);
create index equipment_items_deleted_by_idx on public.equipment_items (deleted_by);

create trigger set_equipment_items_updated_at
  before update on public.equipment_items
  for each row
  execute function public.set_updated_at();

alter table public.equipment_items enable row level security;

create policy "equipment_items_select_viewers"
  on public.equipment_items for select
  to authenticated
  using (public.has_permission((select auth.uid()), 'inventory.view'));

create policy "equipment_items_insert_managers"
  on public.equipment_items for insert
  to authenticated
  with check (public.has_permission((select auth.uid()), 'inventory.manage'));

create policy "equipment_items_update_managers"
  on public.equipment_items for update
  to authenticated
  using (public.has_permission((select auth.uid()), 'inventory.manage'))
  with check (public.has_permission((select auth.uid()), 'inventory.manage'));

create policy "equipment_items_delete_managers"
  on public.equipment_items for delete
  to authenticated
  using (public.has_permission((select auth.uid()), 'inventory.manage'));
