-- 0032_equipment_item_movements_expansion: the ONLY other change to a previously-approved
-- table. Widens equipment_item_movements' movement_type vocabulary (additive — every
-- existing value stays valid) and adds nullable columns so warehouse operations can log
-- into the SAME canonical append-only movement ledger instead of a parallel one. No existing
-- row, query, or RLS policy is affected; nothing here is renamed or removed.

alter table public.equipment_item_movements
  drop constraint equipment_item_movements_movement_type_check;

alter table public.equipment_item_movements
  add constraint equipment_item_movements_movement_type_check check (
    movement_type in (
      'initial_placement', 'transfer', 'check_out', 'check_in',
      'receive', 'put_away', 'pick', 'dispatch', 'return', 'repair_transfer',
      'quarantine', 'release', 'scrap', 'cycle_count_adjustment', 'bulk_move'
    )
  );

alter table public.equipment_item_movements
  add column reason text,
  add column warehouse_transfer_id uuid references public.warehouse_transfers (id),
  add column movement_batch_id uuid,
  add column requires_approval boolean not null default false,
  add column approved_by uuid references public.profiles (id),
  add column approved_at timestamptz;

comment on column public.equipment_item_movements.movement_batch_id is
  'Groups rows created together by a single bulk_move operation. Null for individual movements.';
comment on column public.equipment_item_movements.warehouse_transfer_id is
  'Set when this movement was generated by a warehouse_transfers line, so a transfer''s full movement history can be traced back from either side.';

create index equipment_item_movements_warehouse_transfer_id_idx
  on public.equipment_item_movements (warehouse_transfer_id);
create index equipment_item_movements_movement_batch_id_idx
  on public.equipment_item_movements (movement_batch_id);
create index equipment_item_movements_approved_by_idx
  on public.equipment_item_movements (approved_by);
